# Generated by Django 4.0.3 on 2022-03-18 02:43

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title', max_length=240)),
                ('featured_image', models.ImageField(blank=True, help_text='Article image', null=True, upload_to='articles/')),
                ('image_credit', models.CharField(blank=True, max_length=120, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('featured', models.BooleanField(default=False)),
                ('date_stamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='', editable=False, max_length=120)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the event', max_length=150)),
                ('event_date_time', models.DateTimeField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%d')),
                ('registration_link', models.URLField(max_length=500)),
                ('event_location', models.CharField(help_text='Where will the events be happening?', max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('donations', models.FloatField(default=0, help_text='DOnations made for the event')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='Volunteer mobile phone', max_length=50)),
                ('image', models.ImageField(upload_to='volunteers/')),
                ('job_role', models.CharField(max_length=150)),
                ('education', models.CharField(help_text='Volunteer educational background', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_stamp', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(help_text='Select a category that this article belong to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('title', 'slug')},
        ),
    ]
