# Generated by Django 4.0.3 on 2022-03-18 12:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='<p >If you are going to use a <a href='),
            preserve_default=False,
        ),
    ]
