# Generated by Django 4.0.3 on 2022-03-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='social_handle_link',
            field=models.URLField(blank=True, help_text='Volunteer social profile e.g. LinkedIn, Instagram or Twitter.', max_length=500, null=True),
        ),
    ]
