# Generated by Django 4.0.3 on 2022-03-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='goal',
            field=models.FloatField(default=0, help_text='Goal for the event'),
        ),
    ]
