# Generated by Django 4.0.3 on 2022-03-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_volunteer_social_handle_link'),
        ('core', '0004_event_goal'),
    ]

    operations = [
    ]
