# Generated by Django 4.0.3 on 2022-03-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20220319_1149'),
        ('core', '0005_merge_20220319_1551'),
    ]

    operations = [
    ]
