# Generated by Django 4.0.3 on 2022-03-21 17:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20220321_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='persons/')),
                ('job_role', models.CharField(blank=True, max_length=150, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_member_of_board', models.BooleanField(default=False)),
                ('social_handle_link', models.URLField(blank=True, help_text='Person social profile e.g. LinkedIn, Instagram or Twitter.', max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, help_text="Provide an external URL to the article if you don't want to create a content.", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(default='default.jpg', help_text='Article image', upload_to='articles/'),
        ),
    ]
