# Generated by Django 4.0.3 on 2022-03-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_person_delete_volunteer_article_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_logo', models.ImageField(upload_to='partners/')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_staff',
        ),
    ]
