# Generated by Django 4.0.3 on 2022-03-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_partner_remove_person_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default_event.jpg', null=True, upload_to='events/%Y/%m/%d'),
        ),
    ]
